global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mlops_flask_api'
    static_configs:
      - targets: ['localhost:8000'] # Jika Prometheus di Docker, ganti jadi 'host.docker.internal:8000'